In [1]:
# %%
#
# Cell 1: Initial Setup
#
import pandas as pd
import numpy as np
import torch
import random
import os

from transformers import (
    AutoTokenizer, AutoModelForSequenceClassification,
    TrainingArguments, Trainer,
    DataCollatorWithPadding
)

from datasets import Dataset

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score, f1_score, precision_recall_fscore_support,
    matthews_corrcoef, balanced_accuracy_score,
    cohen_kappa_score, jaccard_score, hamming_loss,
    confusion_matrix
)

/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/usr/local/lib/python3.10/dist-packages/torchvision/image.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
2025-06-28 19:23:30.529998: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-06-28 19:23:31.367143: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-06-28 19:23:31.367200: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-06-28 19:23:31.516800: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-06-28 19:23:31.833650: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 AVX_VNNI AMX_TILE AMX_INT8 AMX_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [2]:
# %%
#
# Cell 2: W&B and Hugging Face Login
#
import wandb
import optuna
import huggingface_hub

import os
os.environ["WANDB_PROJECT"] = "distilbert_degendered"

# NOTE: Replace with your actual keys or use environment variables
# wandb.login(key="YOUR_WANDB_KEY")
# huggingface_hub.login(token="YOUR_HF_TOKEN")

In [3]:
# %%
#
# Cell 3: Model Configuration
#
model_name = "distilbert-base-uncased"
model_cache_path = "../scratch/cache/distilbert_degendered"

In [4]:
# %%
#
# Cell 4: Data Preparation
#
# Ensure 'data/combined_letters_degendered.csv' exists at the specified path
df = pd.read_csv("data/combined_letters_degendered.csv")[["full_text", "label"]].dropna()
df["label"] = df["label"].astype(int)

# Perform train-test split, stratifying by label to maintain class distribution
X_train, X_test, y_train, y_test = train_test_split(
    df["full_text"],
    df["label"],
    test_size=0.2,
    stratify=df["label"],
)

# The tokenizer is always loaded from the base model
tokenizer = AutoTokenizer.from_pretrained(model_name, cache_dir=model_cache_path)

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [5]:
# %%
#
# Cell 5: Tokenization
#
# This function prepares your text data for the model by converting it into token IDs
def tokenize(example):
    tokens = tokenizer(
        example["text"],
        truncation=True,
        padding=False,
        max_length=512
    )
    tokens["labels"] = example["label"]
    return tokens

# Convert pandas Series to Hugging Face Dataset objects, then map the tokenization function
train_dataset = Dataset.from_dict({"text": X_train.tolist(), "label": y_train.tolist()})
test_dataset = Dataset.from_dict({"text": X_test.tolist(), "label": y_test.tolist()})

tokenized_train = train_dataset.map(tokenize, batched=True).remove_columns(["text"])
tokenized_test = test_dataset.map(tokenize, batched=True).remove_columns(["text"])

# Data Collator: Dynamically pads input sequences to the longest sequence in the batch
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

Map:   0%|          | 0/7189 [00:00<?, ? examples/s]

Map:   0%|          | 0/1798 [00:00<?, ? examples/s]

In [6]:
# %%
#
# Cell 6: Metrics Function
#
# Compute metrics
def compute_metrics(eval_pred):
    logits, labels = eval_pred

    preds = logits.argmax(-1)
    accuracy = accuracy_score(labels, preds)
    precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average="weighted", zero_division=0)

    print("Confusion Matrix:", confusion_matrix(labels, preds))

    return {
        "f1_score": f1,
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "mcc": matthews_corrcoef(labels, preds),
        "balanced_accuracy": balanced_accuracy_score(labels, preds),
        "cohen_kappa": cohen_kappa_score(labels, preds),
        "jaccard": jaccard_score(labels, preds, average="macro"),
        "hamming_loss": hamming_loss(labels, preds)
    }

In [7]:
# %%
#
# Cell 7: Model Initialization for Hyperparameter Optimization
#
def model_init(trial=None):
    # Load the base pre-trained model (DistilBERT)
    model = AutoModelForSequenceClassification.from_pretrained(
        model_name,
        num_labels=2,
        id2label={0: "female", 1: "male"},
        label2id={"female": 0, "male": 1},
        cache_dir=model_cache_path,
        device_map="auto"
    )
    model.config.pad_token_id = tokenizer.pad_token_id
    return model

In [8]:
# %%
#
# Cell 8: Optuna Hyperparameter Space
#
def optuna_hp_space(trial):
    return {
        "learning_rate": trial.suggest_float("learning_rate", 1e-5, 5e-4, log=True),
        "num_train_epochs": trial.suggest_int("num_train_epochs", 3, 10),
        "per_device_train_batch_size": trial.suggest_categorical("per_device_train_batch_size", [8, 16, 32]),
        "weight_decay": trial.suggest_float("weight_decay", 0.0, 0.03, step=0.01),
    }

In [9]:
# %%
#
# Cell 9: Trainer for Hyperparameter Optimization
#
training_args_for_hpo = TrainingArguments(
    output_dir="../scratch/hpo_results_distilbert_degendered",
    per_device_eval_batch_size=32,
    fp16=True,
    save_strategy="no",
    logging_steps=50,
    report_to="wandb",
    remove_unused_columns=False,
    load_best_model_at_end=False,
    eval_strategy="epoch",
)

trainer = Trainer(
    model_init=model_init,
    args=training_args_for_hpo,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_test,
    tokenizer=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics
)

/tmp/ipykernel_2387882/809944248.py:17: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [10]:
# %%
#
# Cell 10: Run Hyperparameter Search
#
best_run = trainer.hyperparameter_search(
    direction="maximize",
    backend="optuna",
    hp_space=optuna_hp_space,
    n_trials=20,
    compute_objective=lambda metrics: metrics["eval_f1_score"]
)

print("Best run details:")
print(best_run)

# Access the best hyperparameters found by Optuna
best_hps = best_run.hyperparameters
print("Best Hyperparameters Found:")
for hp, value in best_hps.items():
    print(f"  {hp}: {value}")

# W&B will provide a URL to the best run in its logs.
if hasattr(best_run, 'url'):
    print(f"Find the best run and explore all trials in W&B at: {best_run.url}")

[I 2025-06-28 19:24:02,650] A new study created in memory with name: no-name-f5edc67d-bf8f-408f-90e5-6566d3139f09
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Currently logged in as: mtwesley to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[   0  557]
 [   0 1241]]

[I 2025-06-28 19:24:56,760] Trial 0 finished with value: 0.5637066668716401 and parameters: {'learning_rate': 0.0002470472304136043, 'num_train_epochs': 5, 'per_device_train_batch_size': 32, 'weight_decay': 0.02}. Best is trial 0 with value: 0.5637066668716401.
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[   0  557]
 [   0 1241]]

[I 2025-06-28 19:25:34,293] Trial 1 finished with value: 0.5637066668716401 and parameters: {'learning_rate': 0.00026470907363799714, 'num_train_epochs': 3, 'per_device_train_batch_size': 16, 'weight_decay': 0.02}. Best is trial 0 with value: 0.5637066668716401.
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[   0  557]
 [   0 1241]]

[I 2025-06-28 19:26:24,961] Trial 2 finished with value: 0.5637066668716401 and parameters: {'learning_rate': 7.726354104457268e-05, 'num_train_epochs': 3, 'per_device_train_batch_size': 8, 'weight_decay': 0.0}. Best is trial 0 with value: 0.5637066668716401.
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[   0  557]
 [   0 1241]]

[I 2025-06-28 19:28:03,489] Trial 3 finished with value: 0.5637066668716401 and parameters: {'learning_rate': 0.00025110749726873696, 'num_train_epochs': 6, 'per_device_train_batch_size': 8, 'weight_decay': 0.02}. Best is trial 0 with value: 0.5637066668716401.
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[   0  557]
 [   0 1241]]

[I 2025-06-28 19:29:46,667] Trial 4 finished with value: 0.5637066668716401 and parameters: {'learning_rate': 0.0001054492712076354, 'num_train_epochs': 10, 'per_device_train_batch_size': 32, 'weight_decay': 0.02}. Best is trial 0 with value: 0.5637066668716401.
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[   0  557]
 [   0 1241]]

[I 2025-06-28 19:31:11,192] Trial 5 finished with value: 0.5637066668716401 and parameters: {'learning_rate': 0.0001844116090459153, 'num_train_epochs': 7, 'per_device_train_batch_size': 16, 'weight_decay': 0.03}. Best is trial 0 with value: 0.5637066668716401.
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[   0  557]
 [   0 1241]]

[I 2025-06-28 19:32:17,286] Trial 6 finished with value: 0.5637066668716401 and parameters: {'learning_rate': 0.0004159556018019643, 'num_train_epochs': 4, 'per_device_train_batch_size': 8, 'weight_decay': 0.02}. Best is trial 0 with value: 0.5637066668716401.
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[  13  544]
 [   9 1232]]
Confusion Matrix: [[ 134  423]
 [ 135 1106]]
Confusion Matrix: [[ 175  382]
 [ 231 1010]]
Confusion Matrix: [[ 147  410]
 [ 200 1041]]
Confusion Matrix: [[ 174  383]
 [ 232 1009]]

[I 2025-06-28 19:33:20,154] Trial 7 finished with value: 0.6409445585594487 and parameters: {'learning_rate': 2.4674835213265995e-05, 'num_train_epochs': 6, 'per_device_train_batch_size': 32, 'weight_decay': 0.02}. Best is trial 7 with value: 0.6409445585594487.
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[  22  535]
 [  27 1214]]
Confusion Matrix: [[ 112  445]
 [ 156 1085]]

[I 2025-06-28 19:34:02,740] Trial 8 finished with value: 0.6246242659574446 and parameters: {'learning_rate': 5.466863641205789e-05, 'num_train_epochs': 4, 'per_device_train_batch_size': 32, 'weight_decay': 0.03}. Best is trial 7 with value: 0.6409445585594487.
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[   0  557]
 [   0 1241]]

[I 2025-06-28 19:35:15,237] Trial 9 finished with value: 0.5637066668716401 and parameters: {'learning_rate': 0.00045736068810026055, 'num_train_epochs': 6, 'per_device_train_batch_size': 16, 'weight_decay': 0.01}. Best is trial 7 with value: 0.6409445585594487.
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[ 133  424]
 [ 158 1083]]
Confusion Matrix: [[ 121  436]
 [ 137 1104]]
Confusion Matrix: [[ 165  392]
 [ 234 1007]]
Confusion Matrix: [[205 352]
 [316 925]]
Confusion Matrix: [[178 379]
 [269 972]]
Confusion Matrix: [[172 385]
 [256 985]]

[I 2025-06-28 19:36:37,866] Trial 10 finished with value: 0.628954741920625 and parameters: {'learning_rate': 1.5719192527046043e-05, 'num_train_epochs': 8, 'per_device_train_batch_size': 32, 'weight_decay': 0.0}. Best is trial 7 with value: 0.6409445585594487.
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[  82  475]
 [  95 1146]]
Confusion Matrix: [[ 119  438]
 [ 146 1095]]
Confusion Matrix: [[ 106  451]
 [ 150 1091]]
Confusion Matrix: [[208 349]
 [319 922]]
Confusion Matrix: [[173 384]
 [250 991]]
Confusion Matrix: [[170 387]
 [256 985]]

[I 2025-06-28 19:38:00,537] Trial 11 finished with value: 0.6275156845735267 and parameters: {'learning_rate': 1.221152637026815e-05, 'num_train_epochs': 8, 'per_device_train_batch_size': 32, 'weight_decay': 0.0}. Best is trial 7 with value: 0.6409445585594487.
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[ 133  424]
 [ 187 1054]]
Confusion Matrix: [[ 126  431]
 [ 171 1070]]
Confusion Matrix: [[ 159  398]
 [ 238 1003]]
Confusion Matrix: [[209 348]
 [322 919]]
Confusion Matrix: [[193 364]
 [286 955]]
Confusion Matrix: [[168 389]
 [255 986]]
Confusion Matrix: [[163 394]
 [250 991]]

[I 2025-06-28 19:39:34,026] Trial 12 finished with value: 0.6250585158865292 and parameters: {'learning_rate': 1.6906953308455542e-05, 'num_train_epochs': 9, 'per_device_train_batch_size': 32, 'weight_decay': 0.01}. Best is trial 7 with value: 0.6409445585594487.
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[  19  538]
 [  12 1229]]
Confusion Matrix: [[ 165  392]
 [ 218 1023]]
Confusion Matrix: [[  98  459]
 [ 103 1138]]
Confusion Matrix: [[176 381]
 [244 997]]
Confusion Matrix: [[204 353]
 [300 941]]
Confusion Matrix: [[193 364]
 [278 963]]
Confusion Matrix: [[ 176  381]
 [ 240 1001]]

[I 2025-06-28 19:40:57,038] Trial 13 finished with value: 0.6388740976308294 and parameters: {'learning_rate': 2.8044433661447536e-05, 'num_train_epochs': 8, 'per_device_train_batch_size': 32, 'weight_decay': 0.01}. Best is trial 7 with value: 0.6409445585594487.
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[  76  481]
 [  72 1169]]

[I 2025-06-28 19:41:29,143] Trial 14 pruned.
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[  17  540]
 [  13 1228]]
Confusion Matrix: [[ 135  422]
 [ 132 1109]]
Confusion Matrix: [[ 117  440]
 [ 131 1110]]
Confusion Matrix: [[211 346]
 [287 954]]
Confusion Matrix: [[197 360]
 [273 968]]
Confusion Matrix: [[202 355]
 [263 978]]
Confusion Matrix: [[196 361]
 [242 999]]

[I 2025-06-28 19:42:52,241] Trial 15 finished with value: 0.6522443401986705 and parameters: {'learning_rate': 2.962616188065101e-05, 'num_train_epochs': 8, 'per_device_train_batch_size': 32, 'weight_decay': 0.01}. Best is trial 15 with value: 0.6522443401986705.
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[  23  534]
 [  11 1230]]
Confusion Matrix: [[ 132  425]
 [ 151 1090]]
Confusion Matrix: [[  95  462]
 [  95 1146]]
Confusion Matrix: [[200 357]
 [269 972]]
Confusion Matrix: [[ 169  388]
 [ 209 1032]]
Confusion Matrix: [[212 345]
 [276 965]]
Confusion Matrix: [[ 174  383]
 [ 222 1019]]
Confusion Matrix: [[216 341]
 [262 979]]
Confusion Matrix: [[ 203  354]
 [ 238 1003]]

[I 2025-06-28 19:44:35,337] Trial 16 finished with value: 0.6589607956769215 and parameters: {'learning_rate': 3.714346152977037e-05, 'num_train_epochs': 10, 'per_device_train_batch_size': 32, 'weight_decay': 0.03}. Best is trial 16 with value: 0.6589607956769215.
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[   0  557]
 [   0 1241]]

[I 2025-06-28 19:45:07,268] Trial 17 pruned.
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[   5  552]
 [   7 1234]]
Confusion Matrix: [[  51  506]
 [  42 1199]]
Confusion Matrix: [[  94  463]
 [  90 1151]]
Confusion Matrix: [[ 135  422]
 [ 168 1073]]
Confusion Matrix: [[ 152  405]
 [ 206 1035]]
Confusion Matrix: [[175 382]
 [252 989]]

[I 2025-06-28 19:47:33,768] Trial 18 finished with value: 0.6328682430116916 and parameters: {'learning_rate': 4.0204249800207026e-05, 'num_train_epochs': 9, 'per_device_train_batch_size': 8, 'weight_decay': 0.03}. Best is trial 16 with value: 0.6589607956769215.
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[   0  557]
 [   0 1241]]

[I 2025-06-28 19:47:59,025] Trial 19 pruned.

Best run details:
BestRun(run_id='16', objective=0.6589607956769215, hyperparameters={'learning_rate': 3.714346152977037e-05, 'num_train_epochs': 10, 'per_device_train_batch_size': 32, 'weight_decay': 0.03}, run_summary=None)
Best Hyperparameters Found:
  learning_rate: 3.714346152977037e-05
  num_train_epochs: 10
  per_device_train_batch_size: 32
  weight_decay: 0.03

In [11]:
# %%
#
# Cell 11: Final Model Retraining
#
# Re-training the model with the best hyperparameters
best_hps = best_run.hyperparameters

# Re-initialize the base model
final_model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=2,
    id2label={0: "female", 1: "male"},
    label2id={"female": 0, "male": 1},
    cache_dir=model_cache_path,
    device_map="auto"
)

final_model.config.pad_token_id = tokenizer.pad_token_id

# Define TrainingArguments for the final training run
final_model_output_dir = "../scratch/final_distilbert_degendered_model"
final_training_args = TrainingArguments(
    output_dir=final_model_output_dir,
    per_device_train_batch_size=best_hps["per_device_train_batch_size"],
    per_device_eval_batch_size=best_hps["per_device_train_batch_size"],
    num_train_epochs=best_hps["num_train_epochs"],
    learning_rate=best_hps["learning_rate"],
    weight_decay=best_hps["weight_decay"],
    fp16=True,
    save_strategy="epoch",
    logging_steps=50,
    report_to="wandb",
    remove_unused_columns=False,
    load_best_model_at_end=True,
    metric_for_best_model="f1_score",
    eval_strategy="epoch",
    save_total_limit=1,
    run_name="final_distilbert_model_training"
)

# Initialize the Trainer for final training
final_trainer = Trainer(
    model=final_model,
    args=final_training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_test,
    tokenizer=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics
)

# Train the final model
final_trainer.train()

# Evaluate the final (best) model
eval_results = final_trainer.evaluate()
print("Final Model Evaluation Results:")
print(eval_results)

# Save the final trained model and tokenizer
final_trainer.save_model(final_model_output_dir)
tokenizer.save_pretrained(final_model_output_dir)

print(f"Final model and tokenizer saved to: {final_model_output_dir}")

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/tmp/ipykernel_2387882/3922020647.py:42: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  final_trainer = Trainer(

Confusion Matrix: [[   0  557]
 [   0 1241]]
Confusion Matrix: [[  22  535]
 [  11 1230]]
Confusion Matrix: [[  69  488]
 [  74 1167]]
Confusion Matrix: [[ 131  426]
 [ 150 1091]]
Confusion Matrix: [[ 162  395]
 [ 220 1021]]
Confusion Matrix: [[218 339]
 [310 931]]
Confusion Matrix: [[245 312]
 [349 892]]
Confusion Matrix: [[187 370]
 [251 990]]
Confusion Matrix: [[ 182  375]
 [ 240 1001]]
Confusion Matrix: [[187 370]
 [262 979]]

Confusion Matrix: [[ 182  375]
 [ 240 1001]]
Final Model Evaluation Results:
{'eval_loss': 1.4610021114349365, 'eval_f1_score': 0.6431922506997386, 'eval_accuracy': 0.6579532814238043, 'eval_precision': 0.635714223155601, 'eval_recall': 0.6579532814238043, 'eval_mcc': 0.14550140790257343, 'eval_balanced_accuracy': 0.566679011684849, 'eval_cohen_kappa': 0.1429029852712974, 'eval_jaccard': 0.4238935146651428, 'eval_hamming_loss': 0.3420467185761958, 'eval_runtime': 1.0655, 'eval_samples_per_second': 1687.528, 'eval_steps_per_second': 53.498, 'epoch': 10.0}
Final model and tokenizer saved to: ../scratch/final_distilbert_degendered_model