In [1]:
# !pip install wandb

In [2]:
import pandas as pd

from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from src.preprocess import BasicDegenderizer, AdvancedDegenderizer
from src.models import DistilBERTClassifier, RoBERTaClassifier

/usr/local/lib/python3.10/dist-packages/torchvision/datapoints/__init__.py:14: UserWarning: The torchvision.datapoints and torchvision.transforms.v2 namespaces are still Beta. While we do not expect major breaking changes, some APIs may still change according to user feedback. Please submit any feedback you may have in this issue: https://github.com/pytorch/vision/issues/6753, and you can also check out https://github.com/pytorch/vision/issues/7319 to learn more about the APIs that we suspect might involve future changes. You can silence this warning by calling torchvision.disable_beta_transforms_warning().
  warnings.warn(_BETA_TRANSFORMS_WARNING)
/usr/local/lib/python3.10/dist-packages/torchvision/transforms/v2/__init__.py:64: UserWarning: The torchvision.datapoints and torchvision.transforms.v2 namespaces are still Beta. While we do not expect major breaking changes, some APIs may still change according to user feedback. Please submit any feedback you may have in this issue: https://github.com/pytorch/vision/issues/6753, and you can also check out https://github.com/pytorch/vision/issues/7319 to learn more about the APIs that we suspect might involve future changes. You can silence this warning by calling torchvision.disable_beta_transforms_warning().
  warnings.warn(_BETA_TRANSFORMS_WARNING)

In [3]:
# import wandb

In [4]:
# wandb.login(key="5489aee4351c1c3af108d0f20e5191f366756c2c")

Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: Appending key for api.wandb.ai to your netrc file: /home/hice1/mwesley32/.netrc
wandb: Currently logged in as: mtwesley to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

True

In [5]:
# wandb.init(
#     project="NLP-Letters-V2",
#     group="nlp-letters-v2-distilbert-gendered"
# )

In [6]:
DATA_PATH = "data/combined_letters_degendered.csv"
LABEL_COLUMN = "label"
TEXT_COLUMN = "full_text"
DEGENDERIZERS = []

In [7]:
# Load dataset
df = pd.read_csv(DATA_PATH, encoding="ISO-8859-1")
print("Dataset shape:", df.shape)

Dataset shape: (3285, 19)

In [8]:
df.head()

,applicant_id,document,writer_gender,letter_type,applicant_gender,applicant_identify,applicant_identify_group,standardized_lor,us_canadian,usmle_1,usmle_2,applicants_writers,TEXT,full_text,s1,s2,s1_s2,s3,full_text_tokens
0,male_3090,sentence_sets.csv.4358,female,lor,male,white,white,1,1,197,225,male_female,this letter serves as the department of medici...,this letter serves as the department of medici...,FIRST_NAME LAST_NAME * LAST_NAME waived his r...,this letter serves as the department of medici...,FIRST_NAME LAST_NAME * LAST_NAME waived his r...,these letters are written and compiled by the ...,526
1,female_267,sentence_sets.csv.4301,male,lor,female,asian - chinese,asian,1,1,203,227,female_male,this letter is written in support of FIRST_NAM...,this letter is written in support of FIRST_NAM...,this letter is written in support of FIRST_NAM...,she is reliable responsible and well reg...,this letter is written in support of FIRST_NAM...,our residents rotate in both inpatient and amb...,447
2,male_1004,sentence_sets.csv.179,male,lor,male,"hispanic, latino, or of spanish origin - mexic...",hispanic_latino_spanish,1,1,206,237,male_male,comments from anesthesiology rotations : â F...,comments from anesthesiology rotations FIRS...,comments from anesthesiology rotations FIRS...,he had excellent questions to showed his since...,comments from anesthesiology rotations FIRS..., *  *  * works hard always looking for w...,365
3,female_147,sentence_sets.csv.3846,male,lor,female,"hispanic, latino, or of spanish origin - other...",hispanic_latino_spanish,1,1,206,217,female_male,long number ms LAST_NAME had originally planne...,long number ms LAST_NAME had originally planne...,long number ms LAST_NAME had originally planne...,she took full advantage of the opportunity f...,long number ms LAST_NAME had originally planne...,2 I am not aware of any areas that require...,346
4,male_381,sentence_sets.csv.6,female,lor,male,black or african american - african american|b...,black or african american,1,1,210,225,male_female,â i think [ FIRST_NAME ] would be an asset t...,i think [ FIRST_NAME ] would be an asset to a...,i think [ FIRST_NAME ] would be an asset to an...,he's someone I look forward to speaking with a...,i think [ FIRST_NAME ] would be an asset to an...,* ucsd would be fortunate to get to keep this...,512

In [9]:
# advanced_pipeline = Pipeline([("advanced", AdvancedDegenderizer(paths=DEGENDERIZERS))])
# df["degendered"] = advanced_pipeline.fit_transform(df[TEXT_COLUMN].tolist())
# df["gendered"] = df[TEXT_COLUMN]

In [4]:
# # Create degendering pipelines for each degenderizer
# basic_pipeline = Pipeline([("basic", BasicDegenderizer(paths=DEGENDERIZERS))])
# advanced_pipeline = Pipeline([("advanced", AdvancedDegenderizer(paths=DEGENDERIZERS))])

In [27]:
# # Apply both pipelines to the text column
# df["basic_degendered"] = basic_pipeline.fit_transform(df[TEXT_COLUMN].tolist())
# df["advanced_degendered"] = advanced_pipeline.fit_transform(df[TEXT_COLUMN].tolist())

# print(df[[TEXT_COLUMN, "gendered", "degendered"]].head())

                                           full_text  \
0  this letter serves as the department of medici...
1  this letter is written in support of FIRST_NAM...
2  comments from anesthesiology rotations    FIRS...
3  long number ms LAST_NAME had originally planne...
4   i think [ FIRST_NAME ] would be an asset to a...

                                            gendered  \
0  this letter serves as the department of medici...
1  this letter is written in support of FIRST_NAM...
2  comments from anesthesiology rotations    FIRS...
3  long number ms LAST_NAME had originally planne...
4   i think [ FIRST_NAME ] would be an asset to a...

                                          degendered
0  this letter serves as the department of medici...
1  this letter is written in support of FIRST_NAM...
2  comments from anesthesiology rotations    FIRS...
3  long number ms LAST_NAME had originally planne...
4   i think [ FIRST_NAME ] would be an asset to a...

In [6]:
# For training, we use advanced
# df["degendered_text"] = df["advanced_degendered"]

In [10]:
# Convert categorical labels to factors / integers
df["label"], class_mapping = pd.factorize(df["label"])
print("Class mapping:", dict(enumerate(class_mapping)))

Class mapping: {0: 'male', 1: 'female'}

In [11]:
# Train test splits
X_train, X_test, y_train, y_test = train_test_split(
    df["full_text"],
    df["label"],
    test_size=0.2,
    random_state=42,
    stratify=df["label"],
)

print("Train size:", len(X_train), "Test size:", len(X_test))

Train size: 2628 Test size: 657

In [12]:
# DistilBERT classifier model
model = DistilBERTClassifier(
    model_name="distilbert-base-uncased",
    num_labels=len(class_mapping),
)

model.train(
    X_train.tolist(),
    y_train.tolist(),
    epochs=3,
    batch_size=16,
    learning_rate=2e-5,
    weight_decay=0.01,
    report_to=["wandb"]
)

metrics = model.test(X_test.tolist()[0:5], y_test.tolist()[0:5])

print("Evaluation Metrics:", metrics)

Map:   0%|          | 0/2628 [00:00<?, ? examples/s]

/home/hice1/mwesley32/.local/lib/python3.10/site-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
/home/hice1/mwesley32/NLP-Letters-V2/src/models.py:189: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  self.trainer = Trainer(
wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.

Parameter 'function'=<bound method DistilBERTClassifier._tokenize of <src.models.DistilBERTClassifier object at 0x155450bd4730>> of the transform datasets.arrow_dataset.Dataset._map_single couldn't be hashed properly, a random hash was used instead. Make sure your transforms and parameters are serializable with pickle or dill for the dataset fingerprinting and caching to work. If you reuse this transform, the caching mechanism will consider it to be different from the previous calls and recompute everything. This warning is only showed once. Subsequent hashing failures won't be showed.

Map:   0%|          | 0/5 [00:00<?, ? examples/s]

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:386: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:386: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:386: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:708: RuntimeWarning: invalid value encountered in true_divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:386: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(

Evaluation Metrics: {'accuracy': 1.0, 'precision': 1.0, 'recall': 1.0, 'f1': 1.0, 'mcc': 0.0, 'balanced_accuracy': 1.0, 'cohen_kappa': nan, 'jaccard': 1.0, 'hamming_loss': 0.0, 'auc_roc': None, 'auc_pr': None, '0_precision': 1.0, '0_recall': 1.0, '0_f1': 1.0, 'cm_00': 5}

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:386: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:386: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:386: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:708: RuntimeWarning: invalid value encountered in true_divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:386: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(

In [11]:
model = RoBERTaClassifier(
    model_name="roberta-base",
    num_labels=len(class_mapping),
)

config.json:   0%|          | 0.00/481 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/499M [00:00<?, ?B/s]

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-base and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [12]:
model.train(
    X_train.tolist(),
    y_train.tolist(),
    epochs=3,
    batch_size=16,
    learning_rate=2e-5,
    weight_decay=0.01,
    report_to=["wandb"]
)

Map:   0%|          | 0/2628 [00:00<?, ? examples/s]

/home/hice1/mwesley32/.local/lib/python3.10/site-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
/home/hice1/mwesley32/NLP-Letters-V2/src/models.py:394: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  self.trainer = Trainer(

Trainer is attempting to log a value of "[[373, 1], [3, 149]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.
Trainer is attempting to log a value of "{'0': {'precision': 0.9920212765957447, 'recall': 0.9973262032085561, 'f1-score': 0.9946666666666667, 'support': 374.0}, '1': {'precision': 0.9933333333333333, 'recall': 0.9802631578947368, 'f1-score': 0.9867549668874173, 'support': 152.0}, 'accuracy': 0.9923954372623575, 'macro avg': {'precision': 0.992677304964539, 'recall': 0.9887946805516465, 'f1-score': 0.990710816777042, 'support': 526.0}, 'weighted avg': {'precision': 0.9924004260712455, 'recall': 0.9923954372623575, 'f1-score': 0.9923803960080243, 'support': 526.0}}" of type <class 'dict'> for key "eval/classification_report" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.
Trainer is attempting to log a value of "[[374, 0], [4, 148]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.
Trainer is attempting to log a value of "{'0': {'precision': 0.9894179894179894, 'recall': 1.0, 'f1-score': 0.9946808510638298, 'support': 374.0}, '1': {'precision': 1.0, 'recall': 0.9736842105263158, 'f1-score': 0.9866666666666667, 'support': 152.0}, 'accuracy': 0.9923954372623575, 'macro avg': {'precision': 0.9947089947089947, 'recall': 0.986842105263158, 'f1-score': 0.9906737588652482, 'support': 526.0}, 'weighted avg': {'precision': 0.9924759088257188, 'recall': 0.9923954372623575, 'f1-score': 0.9923649650783378, 'support': 526.0}}" of type <class 'dict'> for key "eval/classification_report" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.
Trainer is attempting to log a value of "[[374, 0], [4, 148]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.
Trainer is attempting to log a value of "{'0': {'precision': 0.9894179894179894, 'recall': 1.0, 'f1-score': 0.9946808510638298, 'support': 374.0}, '1': {'precision': 1.0, 'recall': 0.9736842105263158, 'f1-score': 0.9866666666666667, 'support': 152.0}, 'accuracy': 0.9923954372623575, 'macro avg': {'precision': 0.9947089947089947, 'recall': 0.986842105263158, 'f1-score': 0.9906737588652482, 'support': 526.0}, 'weighted avg': {'precision': 0.9924759088257188, 'recall': 0.9923954372623575, 'f1-score': 0.9923649650783378, 'support': 526.0}}" of type <class 'dict'> for key "eval/classification_report" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

Trainer is attempting to log a value of "[[373, 1], [3, 149]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.
Trainer is attempting to log a value of "{'0': {'precision': 0.9920212765957447, 'recall': 0.9973262032085561, 'f1-score': 0.9946666666666667, 'support': 374.0}, '1': {'precision': 0.9933333333333333, 'recall': 0.9802631578947368, 'f1-score': 0.9867549668874173, 'support': 152.0}, 'accuracy': 0.9923954372623575, 'macro avg': {'precision': 0.992677304964539, 'recall': 0.9887946805516465, 'f1-score': 0.990710816777042, 'support': 526.0}, 'weighted avg': {'precision': 0.9924004260712455, 'recall': 0.9923954372623575, 'f1-score': 0.9923803960080243, 'support': 526.0}}" of type <class 'dict'> for key "eval/classification_report" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

{'eval_loss': 0.04746996983885765,
 'eval_accuracy': 0.9923954372623575,
 'eval_precision': 0.992677304964539,
 'eval_recall': 0.9887946805516465,
 'eval_f1': 0.990710816777042,
 'eval_mcc': 0.981464305810839,
 'eval_balanced_accuracy': 0.9887946805516465,
 'eval_cohen_kappa': 0.9814219616430615,
 'eval_jaccard': 0.9816230647873649,
 'eval_hamming_loss': 0.0076045627376425855,
 'eval_auc_roc': 0.9887946805516464,
 'eval_auc_pr': 0.9794314922286704,
 'eval_confusion_matrix': [[373, 1], [3, 149]],
 'eval_classification_report': {'0': {'precision': 0.9920212765957447,
   'recall': 0.9973262032085561,
   'f1-score': 0.9946666666666667,
   'support': 374.0},
  '1': {'precision': 0.9933333333333333,
   'recall': 0.9802631578947368,
   'f1-score': 0.9867549668874173,
   'support': 152.0},
  'accuracy': 0.9923954372623575,
  'macro avg': {'precision': 0.992677304964539,
   'recall': 0.9887946805516465,
   'f1-score': 0.990710816777042,
   'support': 526.0},
  'weighted avg': {'precision': 0.9924004260712455,
   'recall': 0.9923954372623575,
   'f1-score': 0.9923803960080243,
   'support': 526.0}},
 'eval_runtime': 5.5592,
 'eval_samples_per_second': 94.618,
 'eval_steps_per_second': 5.936,
 'epoch': 3.0}

In [10]:
# # DistilBERT classifier model
# model = DistilBERTClassifier(
#     model_name="distilbert-base-uncased",
#     num_labels=len(class_mapping),
# )

In [11]:
# model.train(
#     X_train.tolist(),
#     y_train.tolist(),
#     epochs=3,
#     batch_size=16,
#     learning_rate=2e-5,
#     weight_decay=0.01,
#     output_dir="../scratch/models/distilbert_degendered"
# )

Map:   0%|          | 0/2628 [00:00<?, ? examples/s]

/home/hice1/mwesley32/.local/lib/python3.10/site-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
/home/hice1/mwesley32/NLP-Letters-V2/src/models.py:185: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  self.trainer = Trainer(

Trainer is attempting to log a value of "[[373, 1], [3, 149]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.
Trainer is attempting to log a value of "{'0': {'precision': 0.9920212765957447, 'recall': 0.9973262032085561, 'f1-score': 0.9946666666666667, 'support': 374.0}, '1': {'precision': 0.9933333333333333, 'recall': 0.9802631578947368, 'f1-score': 0.9867549668874173, 'support': 152.0}, 'accuracy': 0.9923954372623575, 'macro avg': {'precision': 0.992677304964539, 'recall': 0.9887946805516465, 'f1-score': 0.990710816777042, 'support': 526.0}, 'weighted avg': {'precision': 0.9924004260712455, 'recall': 0.9923954372623575, 'f1-score': 0.9923803960080243, 'support': 526.0}}" of type <class 'dict'> for key "eval/classification_report" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.
Trainer is attempting to log a value of "[[374, 0], [3, 149]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.
Trainer is attempting to log a value of "{'0': {'precision': 0.9920424403183024, 'recall': 1.0, 'f1-score': 0.996005326231691, 'support': 374.0}, '1': {'precision': 1.0, 'recall': 0.9802631578947368, 'f1-score': 0.9900332225913622, 'support': 152.0}, 'accuracy': 0.9942965779467681, 'macro avg': {'precision': 0.9960212201591512, 'recall': 0.9901315789473684, 'f1-score': 0.9930192744115266, 'support': 526.0}, 'weighted avg': {'precision': 0.9943419632681466, 'recall': 0.9942965779467681, 'f1-score': 0.9942795472329649, 'support': 526.0}}" of type <class 'dict'> for key "eval/classification_report" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.
Trainer is attempting to log a value of "[[374, 0], [3, 149]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.
Trainer is attempting to log a value of "{'0': {'precision': 0.9920424403183024, 'recall': 1.0, 'f1-score': 0.996005326231691, 'support': 374.0}, '1': {'precision': 1.0, 'recall': 0.9802631578947368, 'f1-score': 0.9900332225913622, 'support': 152.0}, 'accuracy': 0.9942965779467681, 'macro avg': {'precision': 0.9960212201591512, 'recall': 0.9901315789473684, 'f1-score': 0.9930192744115266, 'support': 526.0}, 'weighted avg': {'precision': 0.9943419632681466, 'recall': 0.9942965779467681, 'f1-score': 0.9942795472329649, 'support': 526.0}}" of type <class 'dict'> for key "eval/classification_report" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

Trainer is attempting to log a value of "[[374, 0], [3, 149]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.
Trainer is attempting to log a value of "{'0': {'precision': 0.9920424403183024, 'recall': 1.0, 'f1-score': 0.996005326231691, 'support': 374.0}, '1': {'precision': 1.0, 'recall': 0.9802631578947368, 'f1-score': 0.9900332225913622, 'support': 152.0}, 'accuracy': 0.9942965779467681, 'macro avg': {'precision': 0.9960212201591512, 'recall': 0.9901315789473684, 'f1-score': 0.9930192744115266, 'support': 526.0}, 'weighted avg': {'precision': 0.9943419632681466, 'recall': 0.9942965779467681, 'f1-score': 0.9942795472329649, 'support': 526.0}}" of type <class 'dict'> for key "eval/classification_report" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

{'eval_loss': 0.026817413046956062,
 'eval_accuracy': 0.9942965779467681,
 'eval_precision': 0.9960212201591512,
 'eval_recall': 0.9901315789473684,
 'eval_f1': 0.9930192744115266,
 'eval_mcc': 0.9861352114755968,
 'eval_balanced_accuracy': 0.9901315789473684,
 'eval_cohen_kappa': 0.986039104662479,
 'eval_jaccard': 0.9861527991065195,
 'eval_hamming_loss': 0.005703422053231939,
 'eval_auc_roc': 0.9901315789473684,
 'eval_auc_pr': 0.9859665799479688,
 'eval_confusion_matrix': [[374, 0], [3, 149]],
 'eval_classification_report': {'0': {'precision': 0.9920424403183024,
   'recall': 1.0,
   'f1-score': 0.996005326231691,
   'support': 374.0},
  '1': {'precision': 1.0,
   'recall': 0.9802631578947368,
   'f1-score': 0.9900332225913622,
   'support': 152.0},
  'accuracy': 0.9942965779467681,
  'macro avg': {'precision': 0.9960212201591512,
   'recall': 0.9901315789473684,
   'f1-score': 0.9930192744115266,
   'support': 526.0},
  'weighted avg': {'precision': 0.9943419632681466,
   'recall': 0.9942965779467681,
   'f1-score': 0.9942795472329649,
   'support': 526.0}},
 'eval_runtime': 3.1443,
 'eval_samples_per_second': 167.287,
 'eval_steps_per_second': 10.495,
 'epoch': 3.0}

In [14]:
metrics = model.test(X_test.tolist()[0:5], y_test.tolist()[0:5])

print("Evaluation Metrics:", metrics)

Parameter 'function'=<bound method RoBERTaClassifier._tokenize of <src.models.RoBERTaClassifier object at 0x15543baaf700>> of the transform datasets.arrow_dataset.Dataset._map_single couldn't be hashed properly, a random hash was used instead. Make sure your transforms and parameters are serializable with pickle or dill for the dataset fingerprinting and caching to work. If you reuse this transform, the caching mechanism will consider it to be different from the previous calls and recompute everything. This warning is only showed once. Subsequent hashing failures won't be showed.

Map:   0%|          | 0/5 [00:00<?, ? examples/s]

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:386: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:386: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:386: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:708: RuntimeWarning: invalid value encountered in true_divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:386: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(

Evaluation Metrics: {'accuracy': 1.0, 'precision': 1.0, 'recall': 1.0, 'f1': 1.0, 'mcc': 0.0, 'balanced_accuracy': 1.0, 'cohen_kappa': nan, 'jaccard': 1.0, 'hamming_loss': 0.0, 'auc_roc': -1, 'auc_pr': -1, 'confusion_matrix': [[5]], 'classification_report': {'0': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 5.0}, 'accuracy': 1.0, 'macro avg': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 5.0}, 'weighted avg': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 5.0}}}

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:386: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:386: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:386: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:708: RuntimeWarning: invalid value encountered in true_divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:386: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(

In [ ]:
# basic_pipeline

In [ ]:
df["advanced_degendered"] = advanced_pipeline.fit_transform(df[TEXT_COLUMN].tolist())

In [13]:
df["advanced_degendered"][0:5].tolist()

["FIRST_NAME LAST_NAME  * LAST_NAME waived their right to review this letter  * LAST_NAME received a clinical score of outstanding   a theylf board score of satisfactory   and an overall core * LAST_NAME received these comments on their core * \x94 attending e FIRST_NAME performed well on the rotation   specific strengths included actively seeking opportunities for patient care   using strong communication strategies to engender trust with patients   asking for continuous feedback and seeking opportunities to educate team   opportunities infections in hiv    *   attending e it was a pleasure working with FIRST_NAME on wards  * FIRST_NAME's a team player   gets along well with other staff and patients and family  * FIRST_NAME theylped with team work and was active member of the team  * FIRST_NAME has confidence in themself and enjoys the profession they is about to practice   they has a great attitude   that makes working with them to be fun  * \x94 resident in summary   FIRST_NAME completed internal medicine as their first clerkship in their phase il experience and performed very well clinically  * they will FIRST_NAME a strong resident physician  this letter serves as the department of medicine letter for mx  * mx  * mx  * mx  * their presentations were detailed oriented   write ups were well organized and thoughtful  * they took extra initiative in educating the team about various topics including atrial fibrillation personagement   relevance of mxa nares   sleep medications and medication interactions  * they stayed late on several occasions to finish their work and theylp the team  * they commits to patient care and delivers  * great patient ownership   even followed important aspects of patients that they saw before but not seeing that day  * spontaneously researches on patients cases and educates the team with what they learns  * I personally learned from their great positive attitude and disposition  * they showed a strong work ethic during their clerkship within internal medicine   being noted by both unmh and va attendings to be an active member of the team and stay late when needed ",
 "this letter is written in support of FIRST_NAME LAST_NAME's application for a residency position at your institution  * this letter is based on personal observation of and contact with FIRST_NAME as well as on faculty   learner   and peer descriptions of FIRST_NAME's performance in the clinical and academic setting theme at virginia commonwealth university  * FIRST_NAME completed them undergraduate degree   ba   neuroscience   at vanderbilt university in long number they then pursued them medical degree at wake forest school of medicine   which they received in long number * we got to know FIRST_NAME during the interview season as a preliminary medicine candidate  * we were delighted when they matched with us and started in our program in june of long number FIRST_NAME is currently a first year resident in good standing in our preliminary medicine program   july 1   2018 \x94 june 30   2019   anticipated    * based on milestones   FIRST_NAME is effectively progressing in training in all 6 core competencies and is on track to demonstrating performance consistent with expected level of training descriptions in all six core competency areas by the time of completion of them preliminary year  by milestone assessment   them areas of strength are in patient care and medical knowledge  * it is easiest to describe FIRST_NAME's strengths through the words of those with whom they has worked   representative comments from supervising faculty members and fellows     FIRST_NAME is still early in them internship but is performing well on them clinical teams and has demonstrated that they is a well   rounded   enthusiastic   bright   compassionate young physician  they is reliable   responsible   and well   regarded by them peers  * based on our three month experience with them   we have no theysitation in recommending them to you for a position in your program ",
 "comments from anesthesiology rotations    FIRST_NAME was FIRST_NAME excellent student to work with  * they came in every FIRST_NAME prepared and motivated  *  { FIRST_NAME's ] knowledge base was above their peers and they was able to apply it critically and on the fly  *  FIRST_NAME will make FIRST_NAME incredible anesthesiologist * they showed independence and was FIRST_NAME excellent problem   solver  * summary FIRST_NAME had a strong and varied academic background prior to medical school   having been awarded a full scholarship to earn dual ba   bs degrees   psychology & biological sciences   ultimately graduating magna cum laude  * FIRST_NAME was also awarded grant funding for research in art theirtory   psychology that took them to cuzco and machu picchu   writing about the psychology and art of incan child sacrifice  * as a medical student   FIRST_NAME took on a leadership role in organizing on   campus speaking engagements with members of the california state legislature  * they was also chosen as student liaison to uc FIRST_NAME diego school of medicine administration  * they demonstrated FIRST_NAME excellent work ethic and knowledge base and * we are confident that they will be FIRST_NAME asset to the program fortunate enough to match them they had excellent questions to showed their sincere interest in the field  * and i would be happy to have them as a colleague  * they did a great job on their pain medicine rotation   smart and hard working  * during their busy undergraduate years   they found time to volunteer as a counselor for peopletorship and social training of special needs young adults  * they worked on a community outreach project for childhood fitness as director of public relations and government outreach  * their dedication and drive was apparent when they rotated in our department  * they was good at incorporating feedback   easy to teach   and was well   liked by all of our staff  * and we'd be very happy to have them as a resident theme at ucsd  * it is my pleasure to recommend them very highly and without reservation ",
 "long number mx LAST_NAME had originally planned to pursue a career in orthopedic surgery   but finally came to the realization that they is better suited for anesthesiology after spending extensive time researching this career option and working with our attendings to gain a better understanding of general   cardiac   neurosurgery   and pain cases during them 5   week observership theme with us  *   4   mx LAST_NAME has made giving back to the community a priority   even serving as president of augusta university's handy theylpers   a position which enabled them to partner volunteers with community organizations  * I have no doubt that mx LAST_NAME would be a successful and hardworking resident anesthesiologist they took full advantage of the opportunity   functioning as a member of the team   and was open to doing everything from intubating patients to checking anesthesia equipment and retrieving abgs for our residents  * during that same period   they attended all anesthesiology lectures and joined residents during simulation  * they spent them intern year in general surgery   honing them skills in placing invasive lines and taking care of the critically ill in the surgical intensive care unit   an advantage they will bring to any anesthesia residency program  * in addition   they has been a long   time volunteer interpreter for clinica latina   tutor for children in underserved communities in richmond county   and a volunteer in several other clinics associated with our university  * they has indicated them desire for a position in leadership by serving in the academic house senate  * more importantly   by diligently seeking out more information about the specialty of anesthesiology   ensuring that they was going in for the right reasons   making sure it was a specialty they would love to practice before committing to take the final step   speaks volumes to the fact that this decision was not made lightly and they would approach them residency with dedication and passion for the specialty  * and I recommend them wholeheartedly ",
 "i think [ FIRST_NAME ] would be an asset to any institution in any specialty  * it truly was a pleasure getting to work with   teach and get to know FIRST_NAME  *  FIRST_NAME LAST_NAME will make an excellent resident and future leader in anesthesiology  * FIRST_NAME is incredibly smart and fun to work with  * summary FIRST_NAME LAST_NAME has been an exceptional student since they was their high school's salutatorian  * after harvard   FIRST_NAME amassed significant research experience as the ucsf liver   kidney transplant clinical research coordinator over a period where 7 different clinical trials were active  * as a medical student at ucsd   FIRST_NAME has continued to shine as a peopletor   academic liaison   and community outreach volunteer  * during their rotations in our department   FIRST_NAME was a star as you can see from the comments above  they's someone I look forward to speaking with and potentially working with in the future ! \x9d * or they seemed eager and excited to be there and constantly contributed to the care of the patient  * on top of that they also has a great personality   not only when dealing with patients but other physicians and support staff in and around the or  * their knowledge base is above average but most importantly they demonstrated a degree of patient * they was invariably eager to learn and assist our team   but always with a focus on what was best for this patient  * they communicated clearly with patients   families and staff and was a pleasure to work with  *  great medical student   we really need to keep them theme at ucsd ! * i'd love to have them as resident theme ! * they has solid procedural skills and an excellent anesthesia knowledge base  * they will be a top resident in some lucky program ! \x9d * they is always available to theylp   solid fund of knowledge and skills  * they is hard working   took initiative   and eager to learn   * valuable and active member of the anesthesia team   [ will ] be an asset to any residency program they chooses  * they went on to earn a degree in neurobiology at harvard where they became a recruitment officer   giving recruitment talks at various high schools including their alma mater   los angeles senior high school  * they has been a free clinic personager and was chosen to serve on the lcme accreditation committee for the school of medicine  * through their work with the student national medical association   they was able to set up outreach programs for ucsd undergraduates underrepresented in medicine  * multiple evaluators peopletioned wanting to keep them at ucsd   which is a testament to their talent   skill and personality  * we will be aggressively recruiting them to our own program and would be thrilled to have them training with us   though we understand they will be applying throughout the country  * it is my pleasure to give them my highest recommendation without reservation "]

In [26]:
model.test(df["advanced_degendered"][0:5].tolist(), df["label"][0:5])

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

{'accuracy': 0.6, 'precision': 0.3, 'recall': 0.5, 'f1': 0.375}

In [ ]:
# Apply both pipelines to the text column
df["basic_degendered"] = basic_pipeline.transform(df[TEXT_COLUMN].tolist())
df["advanced_degendered"] = advanced_pipeline.transform(df[TEXT_COLUMN].tolist())

print(df[[TEXT_COLUMN, "basic_degendered", "advanced_degendered"]].head())

In [15]:
df["s1_s2"][0]

"FIRST_NAME LAST_NAME  * LAST_NAME waived his right to review this letter  * LAST_NAME received a clinical score of outstanding   a shelf board score of satisfactory   and an overall core * LAST_NAME received these comments on his core * \x94 attending e FIRST_NAME performed well on the rotation   specific strengths included actively seeking opportunities for patient care   using strong communication strategies to engender trust with patients   asking for continuous feedback and seeking opportunities to educate team   opportunities infections in hiv    *   attending e it was a pleasure working with FIRST_NAME on wards  * FIRST_NAME's a team player   gets along well with other staff and patients and family  * FIRST_NAME helped with team work and was active member of the team  * FIRST_NAME has confidence in himself and enjoys the profession he is about to practice   he has a great attitude   that makes working with him to be fun  * \x94 resident in summary   FIRST_NAME completed internal medicine as his first clerkship in his phase il experience and performed very well clinically  * he will FIRST_NAME a strong resident physician  this letter serves as the department of medicine letter for mr  * mr  * mr  * mr  * his presentations were detailed oriented   write ups were well organized and thoughtful  * he took extra initiative in educating the team about various topics including atrial fibrillation management   relevance of mrsa nares   sleep medications and medication interactions  * he stayed late on several occasions to finish his work and help the team  * he commits to patient care and delivers  * great patient ownership   even followed important aspects of patients that he saw before but not seeing that day  * spontaneously researches on patients cases and educates the team with what he learns  * I personally learned from his great positive attitude and disposition  * he showed a strong work ethic during his clerkship within internal medicine   being noted by both unmh and va attendings to be an active member of the team and stay late when needed "

In [21]:
df["advanced_degendered"][0:5]

"FIRST_NAME LAST_NAME  * LAST_NAME waived their right to review this letter  * LAST_NAME received a clinical score of outstanding   a theylf board score of satisfactory   and an overall core * LAST_NAME received these comments on their core * \x94 attending e FIRST_NAME performed well on the rotation   specific strengths included actively seeking opportunities for patient care   using strong communication strategies to engender trust with patients   asking for continuous feedback and seeking opportunities to educate team   opportunities infections in hiv    *   attending e it was a pleasure working with FIRST_NAME on wards  * FIRST_NAME's a team player   gets along well with other staff and patients and family  * FIRST_NAME theylped with team work and was active member of the team  * FIRST_NAME has confidence in themself and enjoys the profession they is about to practice   they has a great attitude   that makes working with them to be fun  * \x94 resident in summary   FIRST_NAME completed internal medicine as their first clerkship in their phase il experience and performed very well clinically  * they will FIRST_NAME a strong resident physician  this letter serves as the department of medicine letter for mx  * mx  * mx  * mx  * their presentations were detailed oriented   write ups were well organized and thoughtful  * they took extra initiative in educating the team about various topics including atrial fibrillation personagement   relevance of mxa nares   sleep medications and medication interactions  * they stayed late on several occasions to finish their work and theylp the team  * they commits to patient care and delivers  * great patient ownership   even followed important aspects of patients that they saw before but not seeing that day  * spontaneously researches on patients cases and educates the team with what they learns  * I personally learned from their great positive attitude and disposition  * they showed a strong work ethic during their clerkship within internal medicine   being noted by both unmh and va attendings to be an active member of the team and stay late when needed "

Allocated: 11.82 GB
Cached: 11.86 GB

3138